# This is a basic workflow to help you get started with Actions

name: Airflow/DAG

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  airflow:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' 

    - uses: actions/setup-java@v1
      with:
        java-version: '9.0.4' 

    - name: Run pip install
      run: |
        pip install -r requirements-airflow.txt
        pip install -r requirements.txt
        
    - name: Configure Airflow
      run: |
        export AIRFLOW_HOME=${{ GITHUB.workspace }}
        airflow upgradedb
        airflow variables -s ENVIRONMENT TEST
        airflow variables -s GSHEET_SPREADSHEET_ID ${{ secrets.GSHEET_SPREADSHEET_ID }}
        echo "GSHEET_SPREADSHEET_ID"
        airflow variables -s GSHEET_PROJECT_ID ${{ secrets.GSHEET_PROJECT_ID }}
        echo "GSHEET_PROJECT_ID"
        airflow variables -s GSHEET_PRIVATE_KEY_ID ${{ secrets.GSHEET_PRIVATE_KEY_ID }}
        echo "GSHEET_PRIVATE_KEY_ID"
        airflow variables -s GSHEET_CLIENT_EMAIL ${{ secrets.GSHEET_CLIENT_EMAIL }}
        echo "GSHEET_CLIENT_EMAIL"
        airflow variables -s GSHEET_CLIENT_ID ${{ secrets.GSHEET_CLIENT_ID }}
        echo "GSHEET_CLIENT_ID"
        airflow variables -s GSHEET_CERT_URL ${{ secrets.GSHEET_CERT_URL }}
        echo "GSHEET_CERT_URL"
        airflow list_dags

    - name: Run DAG tests
      run: |
        export AIRFLOW_HOME=${{ GITHUB.workspace }}
        export ENVIRONMENT=TEST
        airflow test github_poll_trigger check_commits_dromic_covid19_sitreps 2020-04-04
